spring.application.name=keycloak
server.port=8082
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=USER
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/confidata

