name: Backend Redeploy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Backend Deploy
        run: curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}