name: Frontend Redeploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Frontend Deploy
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK }}